name: Push To Nexus

on:
  workflow_call:
    inputs:
      LANGUAGE:
        description: 'Programming language of the package'
        required: true
        type: string
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      NEXUS_DEV_SOURCE:
        required: true
      NEXUS_RELEASE_SOURCE:
        required: true
      NEXUS_API_KEY:
        required: true
      NEXUS_TAG_SOURCE:
        required: true

jobs:
  push_to_nexus_tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment: nexus-approval
    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: nuget-package
          path: ~/artifact

      - name: List files in artifact directory
        run: |
            pwd 
            ls -al ~/artifact/*.jar

      - name: Push to Nexus Repository (Tag)
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_SOURCE: ${{ secrets.NEXUS_TAG_SOURCE }}
          LANGUAGE: ${{ inputs.LANGUAGE }}
        run: |
          echo "Pushing to Nexus repository for tag."
          if [[ "$LANGUAGE" == "java" ]]; then
            # For Java, use mvn deploy
            echo "Using Maven to deploy the package"
            mvn deploy:deploy-file -Dfile=./artifact/*.jar -DgroupId=com.example -DartifactId=nexus-git -Dversion=1.0.0 -Dpackaging=jar -DrepositoryId=nexus -Durl=$NEXUS_SOURCE -Dusername=$NEXUS_USERNAME -Dpassword=$NEXUS_PASSWORD
          elif [[ "$LANGUAGE" == "dotnet" ]]; then
            # For .NET, use dotnet push
            echo "Using .NET to push the package"
            dotnet nuget push ~/artifact/*.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
          elif [[ "$LANGUAGE" == "node" ]]; then
            # For Node, use npm publish
            echo "Using npm to publish the package"
            npm publish ~/artifact --registry $NEXUS_SOURCE --user $NEXUS_USERNAME --password $NEXUS_PASSWORD
          else
            echo "Unsupported language $LANGUAGE"
            exit 1
          fi

  push_to_nexus_branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/release'
    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: nuget-package
          path: ./artifact

      - name: List files in artifact directory
        run: ls -al ./artifact/*.jar

      - name: Push to Nexus Repository (Branch)
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_DEV_SOURCE: ${{ secrets.NEXUS_DEV_SOURCE }}
          NEXUS_RELEASE_SOURCE: ${{ secrets.NEXUS_RELEASE_SOURCE }}
          LANGUAGE: ${{ inputs.LANGUAGE }}
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
            NEXUS_SOURCE=$NEXUS_DEV_SOURCE
          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
            NEXUS_SOURCE=$NEXUS_RELEASE_SOURCE
          fi
          echo "Pushing to Nexus repository: $NEXUS_SOURCE"
          if [[ "$LANGUAGE" == "java" ]]; then
            # For Java, use mvn deploy
            echo "Using Maven to deploy the package"
             mvn deploy:deploy-file -Dfile=./artifact/*.jar -DgroupId=com.example -DartifactId=nexus-git -Dversion=1.0.0 -Dpackaging=jar -DrepositoryId=nexus -Durl=$NEXUS_SOURCE -Dusername=$NEXUS_USERNAME -Dpassword=$NEXUS_PASSWORD
          elif [[ "$LANGUAGE" == "dotnet" ]]; then
            # For .NET, use dotnet push
            echo "Using .NET to push the package"
            dotnet nuget push ~/artifact/*.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
          elif [[ "$LANGUAGE" == "node" ]]; then
            # For Node, use npm publish
            echo "Using npm to publish the package"
            npm publish ~/artifact --registry $NEXUS_SOURCE --user $NEXUS_USERNAME --password $NEXUS_PASSWORD
          else
            echo "Unsupported language $LANGUAGE"
            exit 1
          fi
